### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 88adong88** [Maxmudjon/homebridge-rgb-mqtt#2]
[5/19/2018, 1:49:34 PM] ====================
[5/19/2018, 1:49:34 PM] ERROR LOADING PLUGIN homebridge-rgb-mqtt:
[5/19/2018, 1:49:34 PM] Error: Cannot find module 'mqtt'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-rgb-mqtt/index.js:2:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
[5/19/2018, 1:49:34 PM] ====================

**Comment by Maxmudjon** [comment]
`cd /usr/lib/node_modules/homebridge-rgb-mqtt`
`sudo npm i mqtt --save`
